version: '3'

services:
  # auth service
  redis:
    image: redis
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=AuthService

  auth:
    build:
      context: ../AuthService
      dockerfile: Dockerfile

    environment:
      - NODE_ENV=docker
      - REDIS_HOST=redis
  
  # service
  postgres-backend:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=e-commerce


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 5000:5000
    environment:
      - NODE_ENV=docker



